spring.application.name=finance-tracker-backend
spring.datasource.url=jdbc:postgresql://localhost:5432/finance_tracker
spring.datasource.password=Ri0npl4y
spring.datasource.username=postgres

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=8080


jwt.secret=miClaveSecretaSuperSeguraQueDebeSerLarga123456789
#esto esta en milisegundos quiere decir que en 24 horas el token va a expirar
jwt.expiration=86400000

spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.cache.type=redis