spring.application.name=finance-tracker-backend
spring.datasource.url=${DB_URL}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.username=${DB_USER}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=8080



jwt.secret=${JWT_SECRET}
#esto esta en milisegundos quiere decir que en 24 horas el token va a expirar
jwt.expiration=${JWT_EXPIRATION}
# Solo activo en local, desactivado en produccion
springdoc.api-docs.enabled=false
springdoc.swagger-ui.enabled=false

#spring.data.redis.host={$REDIS_HOST}
#spring.data.redis.port=${REDIS_PORT}
#spring.cache.type=redis
