DB_URL=jdbc:postgresql://localhost:5432/finance_tracker
DB_PASSWORD=Ri0npl4y
DB_USER=postgres

JWT_SECRET=miClaveSecretaSuperSeguraQueDebeSerLarga123456789
JWT_EXPIRATION=86400000
REDIS_HOST=localhost
REDIS_PORT=6379

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

